model_name:
  LightGBM:
    parameters:
      boosting_type: gbdt
      tree_learner: voting
      num_leaves: 20
      max_depth: 5
      learning_rate: 0.1
      n_estimators: 100
      min_data_in_leaf: 200
      lambda_l1: 0
      lambda_l2: 0
      min_gain_to_split: 0
      bagging_fraction: 0.2
      bagging_freq: 1
      feature_fraction: 0.2

  XGBoost:
    parameters:
      num_estimators:
